
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import testcrud.KoneksiDB;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Qoriatul Masfufah
 */
public class mainmenu extends javax.swing.JFrame {

    /**
     * Creates new form mainmenu
     */
    public mainmenu() {
        initComponents();
        setTanggal();
        setJam();
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tanggalbeli = new javax.swing.JLabel();
        jambeli = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbData = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfIDBarang = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfNamaBarang = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfJumlahBarang = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tfHargaBarang = new javax.swing.JTextField();
        Tanggal = new com.toedter.calendar.JDateChooser();
        tfNamaKasir = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btAdd = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btClear = new javax.swing.JButton();
        btRefresh = new javax.swing.JButton();
        btPrint = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Edwardian Script ITC", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("AlfaraBuku");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(220, 0, 180, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Telp. (021) 78990");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(250, 50, 120, 20);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Tanggal");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(660, 20, 60, 20);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Jam");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(660, 50, 60, 20);

        tanggalbeli.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tanggalbeli.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(tanggalbeli);
        tanggalbeli.setBounds(750, 20, 80, 20);

        jambeli.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jambeli.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jambeli);
        jambeli.setBounds(750, 50, 80, 20);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Jln. Basuki-Rahmat N0.22 Malang, Jawa Timur");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(180, 30, 250, 20);

        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\Qoriatul Masfufah\\Pictures\\3.png")); // NOI18N
        jPanel1.add(jLabel13);
        jLabel13.setBounds(-30, 0, 270, 170);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 870, 90);

        tbData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "NamaKasir", "TanggalBeli", "IDBarang", "NamaBarang", "HargaBarang", "JumlahBarang", "Diskon", "Total Harga"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbData);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(250, 180, 590, 250);

        jSeparator1.setName(""); // NOI18N
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(30, 120, 190, 330);

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));
        jPanel3.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Tanggal Pembelian");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(20, 90, 130, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("ID Barang");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(20, 140, 70, 20);
        jPanel3.add(tfIDBarang);
        tfIDBarang.setBounds(20, 160, 180, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Nama Barang");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(20, 190, 80, 20);
        jPanel3.add(tfNamaBarang);
        tfNamaBarang.setBounds(20, 210, 180, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Jumlah Barang");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(20, 290, 90, 20);
        jPanel3.add(tfJumlahBarang);
        tfJumlahBarang.setBounds(20, 310, 180, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Harga Barang");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(20, 240, 90, 20);
        jPanel3.add(tfHargaBarang);
        tfHargaBarang.setBounds(20, 260, 180, 30);
        jPanel3.add(Tanggal);
        Tanggal.setBounds(20, 110, 180, 30);
        jPanel3.add(tfNamaKasir);
        tfNamaKasir.setBounds(20, 50, 180, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Nama Kasir");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(20, 30, 90, 20);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("Kasa1");
        jPanel3.add(jLabel12);
        jLabel12.setBounds(20, 4, 34, 20);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(10, 100, 220, 360);

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));
        jPanel2.setLayout(null);

        btAdd.setText("Add");
        btAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddActionPerformed(evt);
            }
        });
        jPanel2.add(btAdd);
        btAdd.setBounds(30, 10, 90, 30);

        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(140, 10, 90, 30);

        btClear.setText("Clear");
        btClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClearActionPerformed(evt);
            }
        });
        jPanel2.add(btClear);
        btClear.setBounds(250, 10, 90, 30);

        btRefresh.setText("Refresh");
        btRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRefreshActionPerformed(evt);
            }
        });
        jPanel2.add(btRefresh);
        btRefresh.setBounds(370, 10, 100, 30);

        btPrint.setText("Print");
        btPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPrintActionPerformed(evt);
            }
        });
        jPanel2.add(btPrint);
        btPrint.setBounds(500, 10, 90, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(240, 100, 610, 50);

        jPanel4.setBackground(new java.awt.Color(204, 255, 255));
        jPanel4.setForeground(new java.awt.Color(204, 255, 255));
        getContentPane().add(jPanel4);
        jPanel4.setBounds(240, 160, 610, 290);

        jPanel5.setBackground(new java.awt.Color(0, 204, 204));
        getContentPane().add(jPanel5);
        jPanel5.setBounds(0, 90, 870, 390);

        setBounds(0, 0, 884, 515);
    }// </editor-fold>//GEN-END:initComponents

    private void btAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddActionPerformed
        // TODO add your handling code here:
        
         SimpleDateFormat dateFormat= new SimpleDateFormat("yyy-MM-dd");
         String tanggal = dateFormat.format(Tanggal.getDate());
       
        if ("".equals(tfNamaKasir.getText())||"".equals(tanggal)||"".equals(tfIDBarang.getText())||"".equals(tfNamaBarang.getText())||"".equals(tfHargaBarang.getText())||"".equals(tfJumlahBarang.getText())) {
           JOptionPane.showMessageDialog(this, "Data nyoba", "Kosong", JOptionPane.WARNING_MESSAGE);
        }else{
            
            
            int hargabarang;
            int jumlahbarang;
            int diskon = 10;
            
            String hargakotor = tfHargaBarang.getText();
            hargabarang = Integer.parseInt(hargakotor);
            
            String jumlahkotor = tfJumlahBarang.getText();
            jumlahbarang = Integer.parseInt(jumlahkotor);
            
            int totalhargabersih;
            
            int subtotal = hargabarang * jumlahbarang;
            
            if(subtotal > 100000){
                int hargakurang = subtotal * (diskon /100);
                totalhargabersih = subtotal - hargakurang;
            }else{
                totalhargabersih = subtotal;
            }
            
            
            String SQL = "INSERT INTO tb_product(id_barang,nama_barang,harga_barang,nama_kasir,jumlah_barang,tanggal_pembelian,diskon,total_harga)" 
                    + "VALUES('"+tfIDBarang.getText()
                    +"','"+tfNamaBarang.getText()
                    +"','"+tfHargaBarang.getText()
                    +"','"+tfNamaKasir.getText()
                    +"','"+tfJumlahBarang.getText()
                    +"','"+tanggal
                    + "','"+diskon
                    +"','"+totalhargabersih+"')";
                    
            int status = KoneksiDB.execute(SQL);
            if(status == 1){
                JOptionPane.showMessageDialog(this,"Data berhasil ditambahkan","Sukses", JOptionPane.INFORMATION_MESSAGE);
                selectedData();
            }
            else{
                JOptionPane.showMessageDialog(this,"Data gagal ditambahkan","Gagal",JOptionPane.WARNING_MESSAGE);
            }
        }
    }                                      

    private void btDeleteActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        
        int baris = tbData.getSelectedRow();
        if (baris != -1){
            String idbarang = tbData.getValueAt(baris, 0).toString();
            String SQL = "DELETE FROM tb_product WHERE id_barang='"+idbarang+"'";
            int status = KoneksiDB.execute(SQL);
            if(status ==1){
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(this, "Data gagal dihapus", "Gagal", JOptionPane.WARNING_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(this,"Pilih Baris Data Terlebih Dahulu", "EROR", JOptionPane.WARNING_MESSAGE);
        }   
    }//GEN-LAST:event_btAddActionPerformed

    private void btRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRefreshActionPerformed
        // TODO add your handling code here:
        
        selectedData();
    }//GEN-LAST:event_btRefreshActionPerformed

    private void btPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPrintActionPerformed
        // TODO add your handling code here:
        MessageFormat header = new MessageFormat("Struk Belanja Alfara Buku");
        MessageFormat footer = new MessageFormat("Page (0,number,integer) ");
        try{
            tbData.print(JTable.PrintMode.FIT_WIDTH,header,footer,true,null,true,null);
        } catch (java.awt.print.PrinterException e){
            System.err.format("Cannot print %s%n", e.getMessage());
        }
        
    }//GEN-LAST:event_btPrintActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int baris = tbData.getSelectedRow();
        if (baris != -1){
            String IDBarang = tbData.getValueAt(baris, 2).toString();
            String SQL = "DELETE FROM tb_product WHERE id_barang='"+IDBarang+"'";
            int status = KoneksiDB.execute(SQL);
            if(status == 1){
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(this, "Data gagal dihapus", "Gagal", JOptionPane.WARNING_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(this,"Pilih Baris Data Terlebih Dahulu", "EROR", JOptionPane.WARNING_MESSAGE);
        } 
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btClearActionPerformed
        // TODO add your handling code here:
        
        tfIDBarang.setText("");
        tfIDBarang.setText("");
        tfNamaBarang.setText("");
        tfHargaBarang.setText("");
        tfJumlahBarang.setText("");
        tfNamaKasir.setText("");
        Tanggal.setCalendar(null);
    }//GEN-LAST:event_btClearActionPerformed

    private void selectedData() {
        String kolom[] = {"NamaKasir","TanggalBeli","IDBarang","NamaBarang","HargaBarang","JumlahBarang","Diskon","HargaTotal"};
                DefaultTableModel dtm = new DefaultTableModel(null, kolom);
                String SQL = "SELECT * FROM tb_product";
                ResultSet rs = KoneksiDB.executeQuery(SQL);
                try{
                    while(rs.next()){
                        String IDBarang     = rs.getString(1);
                        String NamaBarang   = rs.getString(2);
                        String HargaBarang  = rs.getString(3);
                        String NamaKasir    = rs.getString(4);
                        String JumlahBarang = rs.getString(5);
                        String TanggalBeli  = rs.getString(6);
                        String Diskon       = rs.getString(7);
                        String HargaTotal   = rs.getString(8);
                        String data[] = {NamaKasir,TanggalBeli,IDBarang,NamaBarang,HargaBarang,JumlahBarang,Diskon,HargaTotal};
                        dtm.addRow(data);
                    }
                } catch (SQLException ex) {
                    java.util.logging.Logger.getLogger(mainmenu.class.getName()).log(Level.SEVERE, null, ex);
        }
              tbData.setModel(dtm);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainmenu().setVisible(true);
            }
        });
    }
    
    public void setTanggal(){
        java.util.Date skrng            = new java.util.Date();
        java.text.SimpleDateFormat kal  = new java.text.SimpleDateFormat("dd/MM/YYYY");
        tanggalbeli.setText(kal.format(skrng));
    }
    
    public void setJam(){
        ActionListener taskPerformer = new ActionListener(){
            String nol_jam,nol_detik,nol_menit;
            public void actionPerformed(ActionEvent evt){
                Date dt = new Date();
                int nilai_jam = dt.getHours();
                int nilai_menit = dt.getMinutes();
                int nilai_detik = dt.getSeconds();
                if(nilai_jam <= 9){
                    nol_jam = "0";
                }
                if(nilai_detik <= 9){
                    nol_detik = "0";
                }
            String jam  = Integer.toString(nilai_jam);
            String menit =  Integer.toString(nilai_menit);
            String detik = Integer.toString(nilai_detik);
            jambeli.setText("Jam "+jam + ":" + menit + ":" + detik);
            }
        };
    new Timer (100, taskPerformer).start();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser Tanggal;
    private javax.swing.JButton btAdd;
    private javax.swing.JButton btClear;
    private javax.swing.JButton btPrint;
    private javax.swing.JButton btRefresh;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel jambeli;
    private javax.swing.JLabel tanggalbeli;
    private javax.swing.JTable tbData;
    private javax.swing.JTextField tfHargaBarang;
    private javax.swing.JTextField tfIDBarang;
    private javax.swing.JTextField tfJumlahBarang;
    private javax.swing.JTextField tfNamaBarang;
    private javax.swing.JTextField tfNamaKasir;
    // End of variables declaration//GEN-END:variables

    
}
